#!/bin/sh

# Mount virtual filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Setup hostname
if [ -f /etc/hostname ]; then
    hostname -F /etc/hostname
fi

echo "[報告] HorizOS (Fundamental) 起動シーケンスを完了。"
/bin/sh
