#!/bin/sh

# 仮想ファイルシステムをマウント
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# ホスト名のセットアップ
if [ -f /etc/hostname ]; then
    hostname -F /etc/hostname
fi

echo "HorizOS 起動シーケンスを完了。"
/bin/sh
